plugins{
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.1'
    testImplementation 'org.assertj:assertj-core:3.27.7'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'com.google.guava:guava:33.4.6-jre'
}

java{
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application{
    mainClass = 'com.db.DBEntryPoint'
}

test{
    useJUnitPlatform()
}
run{
   standardInput = System.in
}